# Generated by Django 3.0.5 on 2020-07-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos_de_teste', '0001_initial'),
        ('cenarios_de_teste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casodeteste',
            name='cenarioDeTeste',
        ),
        migrations.RemoveField(
            model_name='precondicao',
            name='casoDeTeste',
        ),
        migrations.AlterField(
            model_name='cenariodeteste',
            name='plano_de_teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos_de_teste.PlanoDeTeste'),
        ),
        migrations.DeleteModel(
            name='Acoes',
        ),
        migrations.DeleteModel(
            name='CasoDeTeste',
        ),
        migrations.DeleteModel(
            name='PreCondicao',
        ),
    ]
